//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService {
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataConstant.TypeService", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter.Mode" +
        "l")]
    public enum DataConstantTypeService : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASAP = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOOKING = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CSI = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallBackData", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class CallBackData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Addressk__BackingFieldField;
        
        private string Brandk__BackingFieldField;
        
        private string CabTypek__BackingFieldField;
        
        private string Canalek__BackingFieldField;
        
        private string Cityk__BackingFieldField;
        
        private string CodePromotionk__BackingFieldField;
        
        private string CommentWebFormk__BackingFieldField;
        
        private string CompanyNamek__BackingFieldField;
        
        private string CustomerNamek__BackingFieldField;
        
        private string CustomerSurnamek__BackingFieldField;
        
        private System.DateTime DataLeadCreationk__BackingFieldField;
        
        private System.DateTime DesideredDatak__BackingFieldField;
        
        private System.DateTime DueDatek__BackingFieldField;
        
        private string EMailk__BackingFieldField;
        
        private System.Nullable<bool> FlagPrivacyDuek__BackingFieldField;
        
        private System.Nullable<bool> FlagPrivacyk__BackingFieldField;
        
        private string Fuelk__BackingFieldField;
        
        private string GVWk__BackingFieldField;
        
        private string IdCarek__BackingFieldField;
        
        private string IdLeadSitek__BackingFieldField;
        
        private string InitiativeSourceReportDetailk__BackingFieldField;
        
        private string InitiativeSourceReportk__BackingFieldField;
        
        private string InitiativeSourcek__BackingFieldField;
        
        private string Languagek__BackingFieldField;
        
        private string MobilePhoneNumberk__BackingFieldField;
        
        private string ModelOfInterestk__BackingFieldField;
        
        private string Modelk__BackingFieldField;
        
        private string Nationk__BackingFieldField;
        
        private string PhoneNumberk__BackingFieldField;
        
        private string Powerk__BackingFieldField;
        
        private string Provincek__BackingFieldField;
        
        private string StockSearchedModelk__BackingFieldField;
        
        private string Suspensionk__BackingFieldField;
        
        private string Titlek__BackingFieldField;
        
        private string TypeContactk__BackingFieldField;
        
        private string Typek__BackingFieldField;
        
        private string WheelTypek__BackingFieldField;
        
        private string ZipCodek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Address>k__BackingField", IsRequired=true)]
        public string Addressk__BackingField {
            get {
                return this.Addressk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Addressk__BackingFieldField, value) != true)) {
                    this.Addressk__BackingFieldField = value;
                    this.RaisePropertyChanged("Addressk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Brand>k__BackingField", IsRequired=true)]
        public string Brandk__BackingField {
            get {
                return this.Brandk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Brandk__BackingFieldField, value) != true)) {
                    this.Brandk__BackingFieldField = value;
                    this.RaisePropertyChanged("Brandk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CabType>k__BackingField", IsRequired=true)]
        public string CabTypek__BackingField {
            get {
                return this.CabTypek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CabTypek__BackingFieldField, value) != true)) {
                    this.CabTypek__BackingFieldField = value;
                    this.RaisePropertyChanged("CabTypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Canale>k__BackingField", IsRequired=true)]
        public string Canalek__BackingField {
            get {
                return this.Canalek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Canalek__BackingFieldField, value) != true)) {
                    this.Canalek__BackingFieldField = value;
                    this.RaisePropertyChanged("Canalek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<City>k__BackingField", IsRequired=true)]
        public string Cityk__BackingField {
            get {
                return this.Cityk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Cityk__BackingFieldField, value) != true)) {
                    this.Cityk__BackingFieldField = value;
                    this.RaisePropertyChanged("Cityk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CodePromotion>k__BackingField", IsRequired=true)]
        public string CodePromotionk__BackingField {
            get {
                return this.CodePromotionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePromotionk__BackingFieldField, value) != true)) {
                    this.CodePromotionk__BackingFieldField = value;
                    this.RaisePropertyChanged("CodePromotionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommentWebForm>k__BackingField", IsRequired=true)]
        public string CommentWebFormk__BackingField {
            get {
                return this.CommentWebFormk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentWebFormk__BackingFieldField, value) != true)) {
                    this.CommentWebFormk__BackingFieldField = value;
                    this.RaisePropertyChanged("CommentWebFormk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CompanyName>k__BackingField", IsRequired=true)]
        public string CompanyNamek__BackingField {
            get {
                return this.CompanyNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNamek__BackingFieldField, value) != true)) {
                    this.CompanyNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("CompanyNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CustomerName>k__BackingField", IsRequired=true)]
        public string CustomerNamek__BackingField {
            get {
                return this.CustomerNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNamek__BackingFieldField, value) != true)) {
                    this.CustomerNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("CustomerNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CustomerSurname>k__BackingField", IsRequired=true)]
        public string CustomerSurnamek__BackingField {
            get {
                return this.CustomerSurnamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnamek__BackingFieldField, value) != true)) {
                    this.CustomerSurnamek__BackingFieldField = value;
                    this.RaisePropertyChanged("CustomerSurnamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataLeadCreation>k__BackingField", IsRequired=true)]
        public System.DateTime DataLeadCreationk__BackingField {
            get {
                return this.DataLeadCreationk__BackingFieldField;
            }
            set {
                if ((this.DataLeadCreationk__BackingFieldField.Equals(value) != true)) {
                    this.DataLeadCreationk__BackingFieldField = value;
                    this.RaisePropertyChanged("DataLeadCreationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DesideredData>k__BackingField", IsRequired=true)]
        public System.DateTime DesideredDatak__BackingField {
            get {
                return this.DesideredDatak__BackingFieldField;
            }
            set {
                if ((this.DesideredDatak__BackingFieldField.Equals(value) != true)) {
                    this.DesideredDatak__BackingFieldField = value;
                    this.RaisePropertyChanged("DesideredDatak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DueDate>k__BackingField", IsRequired=true)]
        public System.DateTime DueDatek__BackingField {
            get {
                return this.DueDatek__BackingFieldField;
            }
            set {
                if ((this.DueDatek__BackingFieldField.Equals(value) != true)) {
                    this.DueDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("DueDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EMail>k__BackingField", IsRequired=true)]
        public string EMailk__BackingField {
            get {
                return this.EMailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailk__BackingFieldField, value) != true)) {
                    this.EMailk__BackingFieldField = value;
                    this.RaisePropertyChanged("EMailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FlagPrivacyDue>k__BackingField", IsRequired=true)]
        public System.Nullable<bool> FlagPrivacyDuek__BackingField {
            get {
                return this.FlagPrivacyDuek__BackingFieldField;
            }
            set {
                if ((this.FlagPrivacyDuek__BackingFieldField.Equals(value) != true)) {
                    this.FlagPrivacyDuek__BackingFieldField = value;
                    this.RaisePropertyChanged("FlagPrivacyDuek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FlagPrivacy>k__BackingField", IsRequired=true)]
        public System.Nullable<bool> FlagPrivacyk__BackingField {
            get {
                return this.FlagPrivacyk__BackingFieldField;
            }
            set {
                if ((this.FlagPrivacyk__BackingFieldField.Equals(value) != true)) {
                    this.FlagPrivacyk__BackingFieldField = value;
                    this.RaisePropertyChanged("FlagPrivacyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Fuel>k__BackingField", IsRequired=true)]
        public string Fuelk__BackingField {
            get {
                return this.Fuelk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Fuelk__BackingFieldField, value) != true)) {
                    this.Fuelk__BackingFieldField = value;
                    this.RaisePropertyChanged("Fuelk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GVW>k__BackingField", IsRequired=true)]
        public string GVWk__BackingField {
            get {
                return this.GVWk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GVWk__BackingFieldField, value) != true)) {
                    this.GVWk__BackingFieldField = value;
                    this.RaisePropertyChanged("GVWk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IdCare>k__BackingField", IsRequired=true)]
        public string IdCarek__BackingField {
            get {
                return this.IdCarek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCarek__BackingFieldField, value) != true)) {
                    this.IdCarek__BackingFieldField = value;
                    this.RaisePropertyChanged("IdCarek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IdLeadSite>k__BackingField", IsRequired=true)]
        public string IdLeadSitek__BackingField {
            get {
                return this.IdLeadSitek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLeadSitek__BackingFieldField, value) != true)) {
                    this.IdLeadSitek__BackingFieldField = value;
                    this.RaisePropertyChanged("IdLeadSitek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<InitiativeSourceReportDetail>k__BackingField", IsRequired=true)]
        public string InitiativeSourceReportDetailk__BackingField {
            get {
                return this.InitiativeSourceReportDetailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.InitiativeSourceReportDetailk__BackingFieldField, value) != true)) {
                    this.InitiativeSourceReportDetailk__BackingFieldField = value;
                    this.RaisePropertyChanged("InitiativeSourceReportDetailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<InitiativeSourceReport>k__BackingField", IsRequired=true)]
        public string InitiativeSourceReportk__BackingField {
            get {
                return this.InitiativeSourceReportk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.InitiativeSourceReportk__BackingFieldField, value) != true)) {
                    this.InitiativeSourceReportk__BackingFieldField = value;
                    this.RaisePropertyChanged("InitiativeSourceReportk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<InitiativeSource>k__BackingField", IsRequired=true)]
        public string InitiativeSourcek__BackingField {
            get {
                return this.InitiativeSourcek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.InitiativeSourcek__BackingFieldField, value) != true)) {
                    this.InitiativeSourcek__BackingFieldField = value;
                    this.RaisePropertyChanged("InitiativeSourcek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Language>k__BackingField", IsRequired=true)]
        public string Languagek__BackingField {
            get {
                return this.Languagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Languagek__BackingFieldField, value) != true)) {
                    this.Languagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Languagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MobilePhoneNumber>k__BackingField", IsRequired=true)]
        public string MobilePhoneNumberk__BackingField {
            get {
                return this.MobilePhoneNumberk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneNumberk__BackingFieldField, value) != true)) {
                    this.MobilePhoneNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("MobilePhoneNumberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ModelOfInterest>k__BackingField", IsRequired=true)]
        public string ModelOfInterestk__BackingField {
            get {
                return this.ModelOfInterestk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelOfInterestk__BackingFieldField, value) != true)) {
                    this.ModelOfInterestk__BackingFieldField = value;
                    this.RaisePropertyChanged("ModelOfInterestk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Model>k__BackingField", IsRequired=true)]
        public string Modelk__BackingField {
            get {
                return this.Modelk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Modelk__BackingFieldField, value) != true)) {
                    this.Modelk__BackingFieldField = value;
                    this.RaisePropertyChanged("Modelk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Nation>k__BackingField", IsRequired=true)]
        public string Nationk__BackingField {
            get {
                return this.Nationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Nationk__BackingFieldField, value) != true)) {
                    this.Nationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Nationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PhoneNumber>k__BackingField", IsRequired=true)]
        public string PhoneNumberk__BackingField {
            get {
                return this.PhoneNumberk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberk__BackingFieldField, value) != true)) {
                    this.PhoneNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("PhoneNumberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Power>k__BackingField", IsRequired=true)]
        public string Powerk__BackingField {
            get {
                return this.Powerk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Powerk__BackingFieldField, value) != true)) {
                    this.Powerk__BackingFieldField = value;
                    this.RaisePropertyChanged("Powerk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Province>k__BackingField", IsRequired=true)]
        public string Provincek__BackingField {
            get {
                return this.Provincek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Provincek__BackingFieldField, value) != true)) {
                    this.Provincek__BackingFieldField = value;
                    this.RaisePropertyChanged("Provincek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StockSearchedModel>k__BackingField", IsRequired=true)]
        public string StockSearchedModelk__BackingField {
            get {
                return this.StockSearchedModelk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.StockSearchedModelk__BackingFieldField, value) != true)) {
                    this.StockSearchedModelk__BackingFieldField = value;
                    this.RaisePropertyChanged("StockSearchedModelk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Suspension>k__BackingField", IsRequired=true)]
        public string Suspensionk__BackingField {
            get {
                return this.Suspensionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Suspensionk__BackingFieldField, value) != true)) {
                    this.Suspensionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Suspensionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Title>k__BackingField", IsRequired=true)]
        public string Titlek__BackingField {
            get {
                return this.Titlek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Titlek__BackingFieldField, value) != true)) {
                    this.Titlek__BackingFieldField = value;
                    this.RaisePropertyChanged("Titlek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TypeContact>k__BackingField", IsRequired=true)]
        public string TypeContactk__BackingField {
            get {
                return this.TypeContactk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeContactk__BackingFieldField, value) != true)) {
                    this.TypeContactk__BackingFieldField = value;
                    this.RaisePropertyChanged("TypeContactk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Type>k__BackingField", IsRequired=true)]
        public string Typek__BackingField {
            get {
                return this.Typek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Typek__BackingFieldField, value) != true)) {
                    this.Typek__BackingFieldField = value;
                    this.RaisePropertyChanged("Typek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WheelType>k__BackingField", IsRequired=true)]
        public string WheelTypek__BackingField {
            get {
                return this.WheelTypek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WheelTypek__BackingFieldField, value) != true)) {
                    this.WheelTypek__BackingFieldField = value;
                    this.RaisePropertyChanged("WheelTypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ZipCode>k__BackingField", IsRequired=true)]
        public string ZipCodek__BackingField {
            get {
                return this.ZipCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodek__BackingFieldField, value) != true)) {
                    this.ZipCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("ZipCodek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetAppointmentResult", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class SetAppointmentResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodek__BackingFieldField;
        
        private string ErrorDescriptionk__BackingFieldField;
        
        private bool IsSuccessfulk__BackingFieldField;
        
        private System.DateTime endDatek__BackingFieldField;
        
        private System.DateTime startDatek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ErrorCode>k__BackingField", IsRequired=true)]
        public string ErrorCodek__BackingField {
            get {
                return this.ErrorCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodek__BackingFieldField, value) != true)) {
                    this.ErrorCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("ErrorCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ErrorDescription>k__BackingField", IsRequired=true)]
        public string ErrorDescriptionk__BackingField {
            get {
                return this.ErrorDescriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionk__BackingFieldField, value) != true)) {
                    this.ErrorDescriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("ErrorDescriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsSuccessful>k__BackingField", IsRequired=true)]
        public bool IsSuccessfulk__BackingField {
            get {
                return this.IsSuccessfulk__BackingFieldField;
            }
            set {
                if ((this.IsSuccessfulk__BackingFieldField.Equals(value) != true)) {
                    this.IsSuccessfulk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsSuccessfulk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<endDate>k__BackingField", IsRequired=true)]
        public System.DateTime endDatek__BackingField {
            get {
                return this.endDatek__BackingFieldField;
            }
            set {
                if ((this.endDatek__BackingFieldField.Equals(value) != true)) {
                    this.endDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("endDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<startDate>k__BackingField", IsRequired=true)]
        public System.DateTime startDatek__BackingField {
            get {
                return this.startDatek__BackingFieldField;
            }
            set {
                if ((this.startDatek__BackingFieldField.Equals(value) != true)) {
                    this.startDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("startDatek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCalendarResult", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class GetCalendarResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataScheduler DataSchedulerCalendark__BackingFieldField;
        
        private string ErrorCodek__BackingFieldField;
        
        private string ErrorDescriptionk__BackingFieldField;
        
        private bool IsSuccessfulk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataSchedulerCalendar>k__BackingField", IsRequired=true)]
        public Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataScheduler DataSchedulerCalendark__BackingField {
            get {
                return this.DataSchedulerCalendark__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSchedulerCalendark__BackingFieldField, value) != true)) {
                    this.DataSchedulerCalendark__BackingFieldField = value;
                    this.RaisePropertyChanged("DataSchedulerCalendark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ErrorCode>k__BackingField", IsRequired=true)]
        public string ErrorCodek__BackingField {
            get {
                return this.ErrorCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodek__BackingFieldField, value) != true)) {
                    this.ErrorCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("ErrorCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ErrorDescription>k__BackingField", IsRequired=true)]
        public string ErrorDescriptionk__BackingField {
            get {
                return this.ErrorDescriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionk__BackingFieldField, value) != true)) {
                    this.ErrorDescriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("ErrorDescriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsSuccessful>k__BackingField", IsRequired=true)]
        public bool IsSuccessfulk__BackingField {
            get {
                return this.IsSuccessfulk__BackingFieldField;
            }
            set {
                if ((this.IsSuccessfulk__BackingFieldField.Equals(value) != true)) {
                    this.IsSuccessfulk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsSuccessfulk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataScheduler", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class DataScheduler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.LinkedList<Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataSchedulerHeader> LstColumnk__BackingFieldField;
        
        private System.Collections.Generic.LinkedList<Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataSchedulerRow> LstRowk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LstColumn>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.LinkedList<Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataSchedulerHeader> LstColumnk__BackingField {
            get {
                return this.LstColumnk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LstColumnk__BackingFieldField, value) != true)) {
                    this.LstColumnk__BackingFieldField = value;
                    this.RaisePropertyChanged("LstColumnk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LstRow>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.LinkedList<Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataSchedulerRow> LstRowk__BackingField {
            get {
                return this.LstRowk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LstRowk__BackingFieldField, value) != true)) {
                    this.LstRowk__BackingFieldField = value;
                    this.RaisePropertyChanged("LstRowk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSchedulerHeader", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class DataSchedulerHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ColumnIdk__BackingFieldField;
        
        private string ColumnNamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ColumnId>k__BackingField", IsRequired=true)]
        public int ColumnIdk__BackingField {
            get {
                return this.ColumnIdk__BackingFieldField;
            }
            set {
                if ((this.ColumnIdk__BackingFieldField.Equals(value) != true)) {
                    this.ColumnIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ColumnIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ColumnName>k__BackingField", IsRequired=true)]
        public string ColumnNamek__BackingField {
            get {
                return this.ColumnNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNamek__BackingFieldField, value) != true)) {
                    this.ColumnNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("ColumnNamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSchedulerRow", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class DataSchedulerRow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.LinkedList<Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataSchedulerRowCell> LstDataSchedulerRowCellk__BackingFieldField;
        
        private int RowIdk__BackingFieldField;
        
        private string RowNamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LstDataSchedulerRowCell>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.LinkedList<Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataSchedulerRowCell> LstDataSchedulerRowCellk__BackingField {
            get {
                return this.LstDataSchedulerRowCellk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LstDataSchedulerRowCellk__BackingFieldField, value) != true)) {
                    this.LstDataSchedulerRowCellk__BackingFieldField = value;
                    this.RaisePropertyChanged("LstDataSchedulerRowCellk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RowId>k__BackingField", IsRequired=true)]
        public int RowIdk__BackingField {
            get {
                return this.RowIdk__BackingFieldField;
            }
            set {
                if ((this.RowIdk__BackingFieldField.Equals(value) != true)) {
                    this.RowIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("RowIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RowName>k__BackingField", IsRequired=true)]
        public string RowNamek__BackingField {
            get {
                return this.RowNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.RowNamek__BackingFieldField, value) != true)) {
                    this.RowNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("RowNamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSchedulerRowCell", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class DataSchedulerRowCell : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CellNamek__BackingFieldField;
        
        private int ColumnIdk__BackingFieldField;
        
        private bool IsSelectedk__BackingFieldField;
        
        private int RowIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CellName>k__BackingField", IsRequired=true)]
        public string CellNamek__BackingField {
            get {
                return this.CellNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNamek__BackingFieldField, value) != true)) {
                    this.CellNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("CellNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ColumnId>k__BackingField", IsRequired=true)]
        public int ColumnIdk__BackingField {
            get {
                return this.ColumnIdk__BackingFieldField;
            }
            set {
                if ((this.ColumnIdk__BackingFieldField.Equals(value) != true)) {
                    this.ColumnIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ColumnIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsSelected>k__BackingField", IsRequired=true)]
        public bool IsSelectedk__BackingField {
            get {
                return this.IsSelectedk__BackingFieldField;
            }
            set {
                if ((this.IsSelectedk__BackingFieldField.Equals(value) != true)) {
                    this.IsSelectedk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsSelectedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RowId>k__BackingField", IsRequired=true)]
        public int RowIdk__BackingField {
            get {
                return this.RowIdk__BackingFieldField;
            }
            set {
                if ((this.RowIdk__BackingFieldField.Equals(value) != true)) {
                    this.RowIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("RowIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetDealerParameter", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class SetDealerParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DealerCodek__BackingFieldField;
        
        private string DealerCompanyNamek__BackingFieldField;
        
        private string DealerReferentEMailk__BackingFieldField;
        
        private string DealerResponsiblek__BackingFieldField;
        
        private System.Guid IdLeadk__BackingFieldField;
        
        private string MarketingAccountk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DealerCode>k__BackingField", IsRequired=true)]
        public string DealerCodek__BackingField {
            get {
                return this.DealerCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerCodek__BackingFieldField, value) != true)) {
                    this.DealerCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("DealerCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DealerCompanyName>k__BackingField", IsRequired=true)]
        public string DealerCompanyNamek__BackingField {
            get {
                return this.DealerCompanyNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerCompanyNamek__BackingFieldField, value) != true)) {
                    this.DealerCompanyNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("DealerCompanyNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DealerReferentEMail>k__BackingField", IsRequired=true)]
        public string DealerReferentEMailk__BackingField {
            get {
                return this.DealerReferentEMailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerReferentEMailk__BackingFieldField, value) != true)) {
                    this.DealerReferentEMailk__BackingFieldField = value;
                    this.RaisePropertyChanged("DealerReferentEMailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DealerResponsible>k__BackingField", IsRequired=true)]
        public string DealerResponsiblek__BackingField {
            get {
                return this.DealerResponsiblek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerResponsiblek__BackingFieldField, value) != true)) {
                    this.DealerResponsiblek__BackingFieldField = value;
                    this.RaisePropertyChanged("DealerResponsiblek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IdLead>k__BackingField", IsRequired=true)]
        public System.Guid IdLeadk__BackingField {
            get {
                return this.IdLeadk__BackingFieldField;
            }
            set {
                if ((this.IdLeadk__BackingFieldField.Equals(value) != true)) {
                    this.IdLeadk__BackingFieldField = value;
                    this.RaisePropertyChanged("IdLeadk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MarketingAccount>k__BackingField", IsRequired=true)]
        public string MarketingAccountk__BackingField {
            get {
                return this.MarketingAccountk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketingAccountk__BackingFieldField, value) != true)) {
                    this.MarketingAccountk__BackingFieldField = value;
                    this.RaisePropertyChanged("MarketingAccountk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetDealerResult", Namespace="http://schemas.datacontract.org/2004/07/Reply.Iveco.LeadManagement.Presenter")]
    [System.SerializableAttribute()]
    public partial class SetDealerResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodek__BackingFieldField;
        
        private string ErrorDescriptionk__BackingFieldField;
        
        private bool IsSuccessfulk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ErrorCode>k__BackingField", IsRequired=true)]
        public string ErrorCodek__BackingField {
            get {
                return this.ErrorCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodek__BackingFieldField, value) != true)) {
                    this.ErrorCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("ErrorCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ErrorDescription>k__BackingField", IsRequired=true)]
        public string ErrorDescriptionk__BackingField {
            get {
                return this.ErrorDescriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionk__BackingFieldField, value) != true)) {
                    this.ErrorDescriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("ErrorDescriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsSuccessful>k__BackingField", IsRequired=true)]
        public bool IsSuccessfulk__BackingField {
            get {
                return this.IsSuccessfulk__BackingFieldField;
            }
            set {
                if ((this.IsSuccessfulk__BackingFieldField.Equals(value) != true)) {
                    this.IsSuccessfulk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsSuccessfulk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadManagementService.ILeadManagementService")]
    public interface ILeadManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadManagementService/SetAppointment", ReplyAction="http://tempuri.org/ILeadManagementService/SetAppointmentResponse")]
        Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.SetAppointmentResult SetAppointment(Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataConstantTypeService typeService, Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.CallBackData callbackData, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadManagementService/GetCalendar", ReplyAction="http://tempuri.org/ILeadManagementService/GetCalendarResponse")]
        Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.GetCalendarResult GetCalendar(string country, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadManagementService/SetDealer", ReplyAction="http://tempuri.org/ILeadManagementService/SetDealerResponse")]
        Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.SetDealerResult SetDealer(Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.SetDealerParameter dealerParameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ILeadManagementServiceChannel : Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.ILeadManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LeadManagementServiceClient : System.ServiceModel.ClientBase<Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.ILeadManagementService>, Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.ILeadManagementService {
        
        public LeadManagementServiceClient() {
        }
        
        public LeadManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeadManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.SetAppointmentResult SetAppointment(Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.DataConstantTypeService typeService, Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.CallBackData callbackData, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.SetAppointment(typeService, callbackData, startDate, endDate);
        }
        
        public Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.GetCalendarResult GetCalendar(string country, string language) {
            return base.Channel.GetCalendar(country, language);
        }
        
        public Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.SetDealerResult SetDealer(Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementService.SetDealerParameter dealerParameter) {
            return base.Channel.SetDealer(dealerParameter);
        }
    }
}
