//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4206.
// 
#pragma warning disable 1591

namespace Reply.Iveco.LeadManagement.Web.UI.Test.CrmMobileService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LeadManagementMobileServiceSoap", Namespace="http://tempuri.org/")]
    public partial class LeadManagementMobileService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLanguagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetLeadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LeadManagementMobileService() {
            this.Url = global::Reply.Iveco.LeadManagement.Web.UI.Test.Properties.Settings.Default.Reply_Iveco_LeadManagement_Web_UI_Test_CrmMobileService_LeadManagementMobileService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckLoginCompletedEventHandler CheckLoginCompleted;
        
        /// <remarks/>
        public event GetLanguagesCompletedEventHandler GetLanguagesCompleted;
        
        /// <remarks/>
        public event GetCountriesCompletedEventHandler GetCountriesCompleted;
        
        /// <remarks/>
        public event SetLeadCompletedEventHandler SetLeadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CheckLoginResult CheckLogin(string userName, string password) {
            object[] results = this.Invoke("CheckLogin", new object[] {
                        userName,
                        password});
            return ((CheckLoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLoginAsync(string userName, string password) {
            this.CheckLoginAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void CheckLoginAsync(string userName, string password, object userState) {
            if ((this.CheckLoginOperationCompleted == null)) {
                this.CheckLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLoginOperationCompleted);
            }
            this.InvokeAsync("CheckLogin", new object[] {
                        userName,
                        password}, this.CheckLoginOperationCompleted, userState);
        }
        
        private void OnCheckLoginOperationCompleted(object arg) {
            if ((this.CheckLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLoginCompleted(this, new CheckLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLanguages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetLanguagesResult GetLanguages() {
            object[] results = this.Invoke("GetLanguages", new object[0]);
            return ((GetLanguagesResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetLanguagesAsync() {
            this.GetLanguagesAsync(null);
        }
        
        /// <remarks/>
        public void GetLanguagesAsync(object userState) {
            if ((this.GetLanguagesOperationCompleted == null)) {
                this.GetLanguagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLanguagesOperationCompleted);
            }
            this.InvokeAsync("GetLanguages", new object[0], this.GetLanguagesOperationCompleted, userState);
        }
        
        private void OnGetLanguagesOperationCompleted(object arg) {
            if ((this.GetLanguagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLanguagesCompleted(this, new GetLanguagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCountries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetCountriesResult GetCountries() {
            object[] results = this.Invoke("GetCountries", new object[0]);
            return ((GetCountriesResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetCountriesAsync() {
            this.GetCountriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCountriesAsync(object userState) {
            if ((this.GetCountriesOperationCompleted == null)) {
                this.GetCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountriesOperationCompleted);
            }
            this.InvokeAsync("GetCountries", new object[0], this.GetCountriesOperationCompleted, userState);
        }
        
        private void OnGetCountriesOperationCompleted(object arg) {
            if ((this.GetCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetLead", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetLeadResult SetLead(SetLeadParameter param, System.Guid idOperator) {
            object[] results = this.Invoke("SetLead", new object[] {
                        param,
                        idOperator});
            return ((SetLeadResult)(results[0]));
        }
        
        /// <remarks/>
        public void SetLeadAsync(SetLeadParameter param, System.Guid idOperator) {
            this.SetLeadAsync(param, idOperator, null);
        }
        
        /// <remarks/>
        public void SetLeadAsync(SetLeadParameter param, System.Guid idOperator, object userState) {
            if ((this.SetLeadOperationCompleted == null)) {
                this.SetLeadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLeadOperationCompleted);
            }
            this.InvokeAsync("SetLead", new object[] {
                        param,
                        idOperator}, this.SetLeadOperationCompleted, userState);
        }
        
        private void OnSetLeadOperationCompleted(object arg) {
            if ((this.SetLeadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLeadCompleted(this, new SetLeadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        private SystemUser currentUserField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public SystemUser CurrentUser {
            get {
                return this.currentUserField;
            }
            set {
                this.currentUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemUser {
        
        private System.Nullable<int> businessUnitIdDscField;
        
        private System.Guid systemUserIdField;
        
        private int deletionStateCodeField;
        
        private System.Guid businessUnitIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string fullNameField;
        
        private string nickNameField;
        
        private string domainNameField;
        
        private System.Nullable<bool> isDisabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BusinessUnitIdDsc {
            get {
                return this.businessUnitIdDscField;
            }
            set {
                this.businessUnitIdDscField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SystemUserId {
            get {
                return this.systemUserIdField;
            }
            set {
                this.systemUserIdField = value;
            }
        }
        
        /// <remarks/>
        public int DeletionStateCode {
            get {
                return this.deletionStateCodeField;
            }
            set {
                this.deletionStateCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid BusinessUnitId {
            get {
                return this.businessUnitIdField;
            }
            set {
                this.businessUnitIdField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDisabled {
            get {
                return this.isDisabledField;
            }
            set {
                this.isDisabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetLeadResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetLeadParameter {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.Guid countryIdField;
        
        private System.Guid languageIdField;
        
        private int typeContactCodeField;
        
        private string telephoneNumberField;
        
        private string initiativeSourceField;
        
        private string initiativeSourceReportField;
        
        private string initiativeSourceReportDetailField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid LanguageId {
            get {
                return this.languageIdField;
            }
            set {
                this.languageIdField = value;
            }
        }
        
        /// <remarks/>
        public int TypeContactCode {
            get {
                return this.typeContactCodeField;
            }
            set {
                this.typeContactCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TelephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string InitiativeSource {
            get {
                return this.initiativeSourceField;
            }
            set {
                this.initiativeSourceField = value;
            }
        }
        
        /// <remarks/>
        public string InitiativeSourceReport {
            get {
                return this.initiativeSourceReportField;
            }
            set {
                this.initiativeSourceReportField = value;
            }
        }
        
        /// <remarks/>
        public string InitiativeSourceReportDetail {
            get {
                return this.initiativeSourceReportDetailField;
            }
            set {
                this.initiativeSourceReportDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class New_country {
        
        private System.Nullable<int> createdByDscField;
        
        private string createdByNameField;
        
        private System.Nullable<int> modifiedByDscField;
        
        private string modifiedByNameField;
        
        private System.Nullable<int> new_DefaultLanguageIdDscField;
        
        private string new_DefaultLanguageIdNameField;
        
        private System.Nullable<int> new_LeadAssignedToIdDscField;
        
        private string new_LeadAssignedToIdNameField;
        
        private string new_LeadAssignedToIdYomiNameField;
        
        private System.Nullable<int> new_TeamLeaderOverbookingIdDscField;
        
        private string new_TeamLeaderOverbookingIdNameField;
        
        private string new_TeamLeaderOverbookingIdYomiNameField;
        
        private System.Nullable<int> organizationIdDscField;
        
        private string organizationIdNameField;
        
        private System.Guid new_countryIdField;
        
        private System.Nullable<System.DateTime> createdOnField;
        
        private System.Nullable<System.Guid> createdByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private System.Nullable<System.Guid> modifiedByField;
        
        private System.Nullable<System.Guid> organizationIdField;
        
        private int statecodeField;
        
        private System.Nullable<int> statuscodeField;
        
        private System.Nullable<int> deletionStateCodeField;
        
        private System.Nullable<int> importSequenceNumberField;
        
        private System.Nullable<System.DateTime> overriddenCreatedOnField;
        
        private System.Nullable<int> timeZoneRuleVersionNumberField;
        
        private System.Nullable<int> uTCConversionTimeZoneCodeField;
        
        private string new_nameField;
        
        private System.Nullable<int> new_CSIDaysField;
        
        private System.Nullable<bool> new_CRMDealerField;
        
        private string new_CRMDealerAddressField;
        
        private System.Nullable<int> new_DuplicatedLeadDaysField;
        
        private System.Nullable<System.Guid> new_LeadAssignedToIdField;
        
        private System.Nullable<System.Guid> new_DefaultLanguageIdField;
        
        private System.Nullable<int> new_ASAPEndDaysField;
        
        private System.Nullable<int> new_ASAPStartHoursField;
        
        private System.Nullable<int> new_BookingEndDaysField;
        
        private System.Nullable<int> new_BookingStartDaysField;
        
        private System.Nullable<System.Guid> new_TeamLeaderOverbookingIdField;
        
        private System.Nullable<bool> new_UsedLeadToMarketField;
        
        private string new_organizationnameField;
        
        private string new_NewNameField;
        
        private string new_NewSurnameField;
        
        private string new_NewEmailField;
        
        private string new_UsedNameField;
        
        private string new_UsedsurnameField;
        
        private string new_UsedEmailField;
        
        private System.Nullable<int> new_CSIEndDayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CreatedByDsc {
            get {
                return this.createdByDscField;
            }
            set {
                this.createdByDscField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedByName {
            get {
                return this.createdByNameField;
            }
            set {
                this.createdByNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedByDsc {
            get {
                return this.modifiedByDscField;
            }
            set {
                this.modifiedByDscField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedByName {
            get {
                return this.modifiedByNameField;
            }
            set {
                this.modifiedByNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_DefaultLanguageIdDsc {
            get {
                return this.new_DefaultLanguageIdDscField;
            }
            set {
                this.new_DefaultLanguageIdDscField = value;
            }
        }
        
        /// <remarks/>
        public string New_DefaultLanguageIdName {
            get {
                return this.new_DefaultLanguageIdNameField;
            }
            set {
                this.new_DefaultLanguageIdNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_LeadAssignedToIdDsc {
            get {
                return this.new_LeadAssignedToIdDscField;
            }
            set {
                this.new_LeadAssignedToIdDscField = value;
            }
        }
        
        /// <remarks/>
        public string New_LeadAssignedToIdName {
            get {
                return this.new_LeadAssignedToIdNameField;
            }
            set {
                this.new_LeadAssignedToIdNameField = value;
            }
        }
        
        /// <remarks/>
        public string New_LeadAssignedToIdYomiName {
            get {
                return this.new_LeadAssignedToIdYomiNameField;
            }
            set {
                this.new_LeadAssignedToIdYomiNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_TeamLeaderOverbookingIdDsc {
            get {
                return this.new_TeamLeaderOverbookingIdDscField;
            }
            set {
                this.new_TeamLeaderOverbookingIdDscField = value;
            }
        }
        
        /// <remarks/>
        public string New_TeamLeaderOverbookingIdName {
            get {
                return this.new_TeamLeaderOverbookingIdNameField;
            }
            set {
                this.new_TeamLeaderOverbookingIdNameField = value;
            }
        }
        
        /// <remarks/>
        public string New_TeamLeaderOverbookingIdYomiName {
            get {
                return this.new_TeamLeaderOverbookingIdYomiNameField;
            }
            set {
                this.new_TeamLeaderOverbookingIdYomiNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OrganizationIdDsc {
            get {
                return this.organizationIdDscField;
            }
            set {
                this.organizationIdDscField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationIdName {
            get {
                return this.organizationIdNameField;
            }
            set {
                this.organizationIdNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid New_countryId {
            get {
                return this.new_countryIdField;
            }
            set {
                this.new_countryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> OrganizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        public int statecode {
            get {
                return this.statecodeField;
            }
            set {
                this.statecodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> statuscode {
            get {
                return this.statuscodeField;
            }
            set {
                this.statuscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletionStateCode {
            get {
                return this.deletionStateCodeField;
            }
            set {
                this.deletionStateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ImportSequenceNumber {
            get {
                return this.importSequenceNumberField;
            }
            set {
                this.importSequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OverriddenCreatedOn {
            get {
                return this.overriddenCreatedOnField;
            }
            set {
                this.overriddenCreatedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TimeZoneRuleVersionNumber {
            get {
                return this.timeZoneRuleVersionNumberField;
            }
            set {
                this.timeZoneRuleVersionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UTCConversionTimeZoneCode {
            get {
                return this.uTCConversionTimeZoneCodeField;
            }
            set {
                this.uTCConversionTimeZoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string New_name {
            get {
                return this.new_nameField;
            }
            set {
                this.new_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_CSIDays {
            get {
                return this.new_CSIDaysField;
            }
            set {
                this.new_CSIDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> New_CRMDealer {
            get {
                return this.new_CRMDealerField;
            }
            set {
                this.new_CRMDealerField = value;
            }
        }
        
        /// <remarks/>
        public string New_CRMDealerAddress {
            get {
                return this.new_CRMDealerAddressField;
            }
            set {
                this.new_CRMDealerAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_DuplicatedLeadDays {
            get {
                return this.new_DuplicatedLeadDaysField;
            }
            set {
                this.new_DuplicatedLeadDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> New_LeadAssignedToId {
            get {
                return this.new_LeadAssignedToIdField;
            }
            set {
                this.new_LeadAssignedToIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> New_DefaultLanguageId {
            get {
                return this.new_DefaultLanguageIdField;
            }
            set {
                this.new_DefaultLanguageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_ASAPEndDays {
            get {
                return this.new_ASAPEndDaysField;
            }
            set {
                this.new_ASAPEndDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_ASAPStartHours {
            get {
                return this.new_ASAPStartHoursField;
            }
            set {
                this.new_ASAPStartHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_BookingEndDays {
            get {
                return this.new_BookingEndDaysField;
            }
            set {
                this.new_BookingEndDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_BookingStartDays {
            get {
                return this.new_BookingStartDaysField;
            }
            set {
                this.new_BookingStartDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> New_TeamLeaderOverbookingId {
            get {
                return this.new_TeamLeaderOverbookingIdField;
            }
            set {
                this.new_TeamLeaderOverbookingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> New_UsedLeadToMarket {
            get {
                return this.new_UsedLeadToMarketField;
            }
            set {
                this.new_UsedLeadToMarketField = value;
            }
        }
        
        /// <remarks/>
        public string New_organizationname {
            get {
                return this.new_organizationnameField;
            }
            set {
                this.new_organizationnameField = value;
            }
        }
        
        /// <remarks/>
        public string New_NewName {
            get {
                return this.new_NewNameField;
            }
            set {
                this.new_NewNameField = value;
            }
        }
        
        /// <remarks/>
        public string New_NewSurname {
            get {
                return this.new_NewSurnameField;
            }
            set {
                this.new_NewSurnameField = value;
            }
        }
        
        /// <remarks/>
        public string New_NewEmail {
            get {
                return this.new_NewEmailField;
            }
            set {
                this.new_NewEmailField = value;
            }
        }
        
        /// <remarks/>
        public string New_UsedName {
            get {
                return this.new_UsedNameField;
            }
            set {
                this.new_UsedNameField = value;
            }
        }
        
        /// <remarks/>
        public string New_Usedsurname {
            get {
                return this.new_UsedsurnameField;
            }
            set {
                this.new_UsedsurnameField = value;
            }
        }
        
        /// <remarks/>
        public string New_UsedEmail {
            get {
                return this.new_UsedEmailField;
            }
            set {
                this.new_UsedEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_CSIEndDay {
            get {
                return this.new_CSIEndDayField;
            }
            set {
                this.new_CSIEndDayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        private New_country[] countriesField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public New_country[] Countries {
            get {
                return this.countriesField;
            }
            set {
                this.countriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class New_language {
        
        private System.Nullable<int> new_QueueOverbookingIdDscField;
        
        private string new_QueueOverbookingIdNameField;
        
        private System.Guid new_languageIdField;
        
        private System.Nullable<int> deletionStateCodeField;
        
        private string new_nameField;
        
        private System.Nullable<int> new_SlotDurationField;
        
        private System.Nullable<System.Guid> new_QueueOverbookingIdField;
        
        private System.Nullable<System.DateTime> new_BookingStartHourField;
        
        private System.Nullable<System.DateTime> new_BookingEndHourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_QueueOverbookingIdDsc {
            get {
                return this.new_QueueOverbookingIdDscField;
            }
            set {
                this.new_QueueOverbookingIdDscField = value;
            }
        }
        
        /// <remarks/>
        public string New_QueueOverbookingIdName {
            get {
                return this.new_QueueOverbookingIdNameField;
            }
            set {
                this.new_QueueOverbookingIdNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid New_languageId {
            get {
                return this.new_languageIdField;
            }
            set {
                this.new_languageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletionStateCode {
            get {
                return this.deletionStateCodeField;
            }
            set {
                this.deletionStateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string New_name {
            get {
                return this.new_nameField;
            }
            set {
                this.new_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> New_SlotDuration {
            get {
                return this.new_SlotDurationField;
            }
            set {
                this.new_SlotDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> New_QueueOverbookingId {
            get {
                return this.new_QueueOverbookingIdField;
            }
            set {
                this.new_QueueOverbookingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> New_BookingStartHour {
            get {
                return this.new_BookingStartHourField;
            }
            set {
                this.new_BookingStartHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> New_BookingEndHour {
            get {
                return this.new_BookingEndHourField;
            }
            set {
                this.new_BookingEndHourField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLanguagesResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        private New_language[] languagesField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public New_language[] Languages {
            get {
                return this.languagesField;
            }
            set {
                this.languagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void CheckLoginCompletedEventHandler(object sender, CheckLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckLoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckLoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetLanguagesCompletedEventHandler(object sender, GetLanguagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLanguagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLanguagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetLanguagesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetLanguagesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetCountriesCompletedEventHandler(object sender, GetCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetCountriesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetCountriesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SetLeadCompletedEventHandler(object sender, SetLeadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetLeadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetLeadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetLeadResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetLeadResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591