//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4211
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4211.
// 
#pragma warning disable 1591

namespace Reply.Iveco.LeadManagement.Web.UI.Test.LeadManagementServiceBase {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LeadManagementServicesSoap", Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class LeadManagementServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private HeaderAuthentication headerAuthenticationValueField;
        
        private System.Threading.SendOrPostCallback SetAppointmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCalendarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDealerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDealerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LeadManagementServices() {
            this.Url = global::Reply.Iveco.LeadManagement.Web.UI.Test.Properties.Settings.Default.Reply_Iveco_LeadManagement_Web_UI_Test_LeadManagementServiceBase_LeadManagementServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public HeaderAuthentication HeaderAuthenticationValue {
            get {
                return this.headerAuthenticationValueField;
            }
            set {
                this.headerAuthenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetAppointmentCompletedEventHandler SetAppointmentCompleted;
        
        /// <remarks/>
        public event GetCalendarCompletedEventHandler GetCalendarCompleted;
        
        /// <remarks/>
        public event SetDealerCompletedEventHandler SetDealerCompleted;
        
        /// <remarks/>
        public event GetDealerCompletedEventHandler GetDealerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("_http://schemas.microsoft.com/crm/2006/WebServices/SetAppointment", RequestNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetAppointmentResult SetAppointment(string serviceType, CallBackData callbackData, System.DateTime startDate, System.DateTime endDate) {
            object[] results = this.Invoke("SetAppointment", new object[] {
                        serviceType,
                        callbackData,
                        startDate,
                        endDate});
            return ((SetAppointmentResult)(results[0]));
        }
        
        /// <remarks/>
        public void SetAppointmentAsync(string serviceType, CallBackData callbackData, System.DateTime startDate, System.DateTime endDate) {
            this.SetAppointmentAsync(serviceType, callbackData, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void SetAppointmentAsync(string serviceType, CallBackData callbackData, System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.SetAppointmentOperationCompleted == null)) {
                this.SetAppointmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAppointmentOperationCompleted);
            }
            this.InvokeAsync("SetAppointment", new object[] {
                        serviceType,
                        callbackData,
                        startDate,
                        endDate}, this.SetAppointmentOperationCompleted, userState);
        }
        
        private void OnSetAppointmentOperationCompleted(object arg) {
            if ((this.SetAppointmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAppointmentCompleted(this, new SetAppointmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("_http://schemas.microsoft.com/crm/2006/WebServices/GetCalendar", RequestNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetCalendarResult GetCalendar(string country, string language) {
            object[] results = this.Invoke("GetCalendar", new object[] {
                        country,
                        language});
            return ((GetCalendarResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetCalendarAsync(string country, string language) {
            this.GetCalendarAsync(country, language, null);
        }
        
        /// <remarks/>
        public void GetCalendarAsync(string country, string language, object userState) {
            if ((this.GetCalendarOperationCompleted == null)) {
                this.GetCalendarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCalendarOperationCompleted);
            }
            this.InvokeAsync("GetCalendar", new object[] {
                        country,
                        language}, this.GetCalendarOperationCompleted, userState);
        }
        
        private void OnGetCalendarOperationCompleted(object arg) {
            if ((this.GetCalendarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCalendarCompleted(this, new GetCalendarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("_http://schemas.microsoft.com/crm/2006/WebServices/SetDealer", RequestNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetDealerResult SetDealer(SetDealerParameter dealerParameter) {
            object[] results = this.Invoke("SetDealer", new object[] {
                        dealerParameter});
            return ((SetDealerResult)(results[0]));
        }
        
        /// <remarks/>
        public void SetDealerAsync(SetDealerParameter dealerParameter) {
            this.SetDealerAsync(dealerParameter, null);
        }
        
        /// <remarks/>
        public void SetDealerAsync(SetDealerParameter dealerParameter, object userState) {
            if ((this.SetDealerOperationCompleted == null)) {
                this.SetDealerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDealerOperationCompleted);
            }
            this.InvokeAsync("SetDealer", new object[] {
                        dealerParameter}, this.SetDealerOperationCompleted, userState);
        }
        
        private void OnSetDealerOperationCompleted(object arg) {
            if ((this.SetDealerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDealerCompleted(this, new SetDealerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("_http://schemas.microsoft.com/crm/2006/WebServices/GetDealer", RequestNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetDealerResult GetDealer(GetDealerParameter dealerParameter) {
            object[] results = this.Invoke("GetDealer", new object[] {
                        dealerParameter});
            return ((GetDealerResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDealerAsync(GetDealerParameter dealerParameter) {
            this.GetDealerAsync(dealerParameter, null);
        }
        
        /// <remarks/>
        public void GetDealerAsync(GetDealerParameter dealerParameter, object userState) {
            if ((this.GetDealerOperationCompleted == null)) {
                this.GetDealerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDealerOperationCompleted);
            }
            this.InvokeAsync("GetDealer", new object[] {
                        dealerParameter}, this.GetDealerOperationCompleted, userState);
        }
        
        private void OnGetDealerOperationCompleted(object arg) {
            if ((this.GetDealerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDealerCompleted(this, new GetDealerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices", IsNullable=false)]
    public partial class HeaderAuthentication : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class GetDealerResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        private string dealerCompanyNameField;
        
        private string dealerCodeField;
        
        private string dealerResponsibleField;
        
        private string dealerEmailField;
        
        private string marketingAccountField;
        
        private string emailMarketingAccountField;
        
        private bool isCriticalCustomerField;
        
        private int criticalReasonCodeField;
        
        private string dealerManagerNameField;
        
        private string dealerManagerMailField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DealerCompanyName {
            get {
                return this.dealerCompanyNameField;
            }
            set {
                this.dealerCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        public string DealerCode {
            get {
                return this.dealerCodeField;
            }
            set {
                this.dealerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DealerResponsible {
            get {
                return this.dealerResponsibleField;
            }
            set {
                this.dealerResponsibleField = value;
            }
        }
        
        /// <remarks/>
        public string DealerEmail {
            get {
                return this.dealerEmailField;
            }
            set {
                this.dealerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string MarketingAccount {
            get {
                return this.marketingAccountField;
            }
            set {
                this.marketingAccountField = value;
            }
        }
        
        /// <remarks/>
        public string EmailMarketingAccount {
            get {
                return this.emailMarketingAccountField;
            }
            set {
                this.emailMarketingAccountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCriticalCustomer {
            get {
                return this.isCriticalCustomerField;
            }
            set {
                this.isCriticalCustomerField = value;
            }
        }
        
        /// <remarks/>
        public int CriticalReasonCode {
            get {
                return this.criticalReasonCodeField;
            }
            set {
                this.criticalReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DealerManagerName {
            get {
                return this.dealerManagerNameField;
            }
            set {
                this.dealerManagerNameField = value;
            }
        }
        
        /// <remarks/>
        public string DealerManagerMail {
            get {
                return this.dealerManagerMailField;
            }
            set {
                this.dealerManagerMailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class GetDealerParameter {
        
        private bool isFlagCriticoField;
        
        private int leadTypeField;
        
        private string zipCodeField;
        
        private System.Guid countryIdField;
        
        /// <remarks/>
        public bool IsFlagCritico {
            get {
                return this.isFlagCriticoField;
            }
            set {
                this.isFlagCriticoField = value;
            }
        }
        
        /// <remarks/>
        public int LeadType {
            get {
                return this.leadTypeField;
            }
            set {
                this.leadTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class SetDealerResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class SetDealerParameter {
        
        private string idLeadCrmField;
        
        private string dealerCompanyNameField;
        
        private string dealerCodeField;
        
        private string dealerResponsibleField;
        
        private string dealerEmailField;
        
        private string marketingAccountField;
        
        private string emailMarketingAccountField;
        
        private bool isDealerAgreeField;
        
        private bool isCriticalCustomerField;
        
        private int criticalReasonCodeField;
        
        /// <remarks/>
        public string IdLeadCrm {
            get {
                return this.idLeadCrmField;
            }
            set {
                this.idLeadCrmField = value;
            }
        }
        
        /// <remarks/>
        public string DealerCompanyName {
            get {
                return this.dealerCompanyNameField;
            }
            set {
                this.dealerCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        public string DealerCode {
            get {
                return this.dealerCodeField;
            }
            set {
                this.dealerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DealerResponsible {
            get {
                return this.dealerResponsibleField;
            }
            set {
                this.dealerResponsibleField = value;
            }
        }
        
        /// <remarks/>
        public string DealerEmail {
            get {
                return this.dealerEmailField;
            }
            set {
                this.dealerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string MarketingAccount {
            get {
                return this.marketingAccountField;
            }
            set {
                this.marketingAccountField = value;
            }
        }
        
        /// <remarks/>
        public string EmailMarketingAccount {
            get {
                return this.emailMarketingAccountField;
            }
            set {
                this.emailMarketingAccountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDealerAgree {
            get {
                return this.isDealerAgreeField;
            }
            set {
                this.isDealerAgreeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCriticalCustomer {
            get {
                return this.isCriticalCustomerField;
            }
            set {
                this.isCriticalCustomerField = value;
            }
        }
        
        /// <remarks/>
        public int CriticalReasonCode {
            get {
                return this.criticalReasonCodeField;
            }
            set {
                this.criticalReasonCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class DataSchedulerRowCell {
        
        private System.Guid rowIdField;
        
        private System.Guid columnIdField;
        
        private string cellNameField;
        
        private System.DateTime cellDateField;
        
        private int availableSlotField;
        
        private int occupationASAPField;
        
        private int occupationCSIField;
        
        private int occupationBookingField;
        
        private int conflictASAPField;
        
        private int conflictCSIField;
        
        private int conflictBookingField;
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ColumnId {
            get {
                return this.columnIdField;
            }
            set {
                this.columnIdField = value;
            }
        }
        
        /// <remarks/>
        public string CellName {
            get {
                return this.cellNameField;
            }
            set {
                this.cellNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CellDate {
            get {
                return this.cellDateField;
            }
            set {
                this.cellDateField = value;
            }
        }
        
        /// <remarks/>
        public int AvailableSlot {
            get {
                return this.availableSlotField;
            }
            set {
                this.availableSlotField = value;
            }
        }
        
        /// <remarks/>
        public int OccupationASAP {
            get {
                return this.occupationASAPField;
            }
            set {
                this.occupationASAPField = value;
            }
        }
        
        /// <remarks/>
        public int OccupationCSI {
            get {
                return this.occupationCSIField;
            }
            set {
                this.occupationCSIField = value;
            }
        }
        
        /// <remarks/>
        public int OccupationBooking {
            get {
                return this.occupationBookingField;
            }
            set {
                this.occupationBookingField = value;
            }
        }
        
        /// <remarks/>
        public int ConflictASAP {
            get {
                return this.conflictASAPField;
            }
            set {
                this.conflictASAPField = value;
            }
        }
        
        /// <remarks/>
        public int ConflictCSI {
            get {
                return this.conflictCSIField;
            }
            set {
                this.conflictCSIField = value;
            }
        }
        
        /// <remarks/>
        public int ConflictBooking {
            get {
                return this.conflictBookingField;
            }
            set {
                this.conflictBookingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class DataSchedulerRow {
        
        private System.Guid rowIdField;
        
        private string rowNameField;
        
        private System.DateTime startTimeSlotField;
        
        private System.DateTime endTimeSlotField;
        
        private DataSchedulerRowCell[] dataSchedulerRowCellField;
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public string RowName {
            get {
                return this.rowNameField;
            }
            set {
                this.rowNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTimeSlot {
            get {
                return this.startTimeSlotField;
            }
            set {
                this.startTimeSlotField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndTimeSlot {
            get {
                return this.endTimeSlotField;
            }
            set {
                this.endTimeSlotField = value;
            }
        }
        
        /// <remarks/>
        public DataSchedulerRowCell[] DataSchedulerRowCell {
            get {
                return this.dataSchedulerRowCellField;
            }
            set {
                this.dataSchedulerRowCellField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class DataScheduler {
        
        private System.DateTime startDateSchedulerField;
        
        private System.DateTime endDateSchedulerField;
        
        private DataSchedulerRow[] schedulerRowsField;
        
        /// <remarks/>
        public System.DateTime StartDateScheduler {
            get {
                return this.startDateSchedulerField;
            }
            set {
                this.startDateSchedulerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDateScheduler {
            get {
                return this.endDateSchedulerField;
            }
            set {
                this.endDateSchedulerField = value;
            }
        }
        
        /// <remarks/>
        public DataSchedulerRow[] SchedulerRows {
            get {
                return this.schedulerRowsField;
            }
            set {
                this.schedulerRowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class GetCalendarResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        private DataScheduler dataSchedulerCalendarField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public DataScheduler DataSchedulerCalendar {
            get {
                return this.dataSchedulerCalendarField;
            }
            set {
                this.dataSchedulerCalendarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class SetAppointmentResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class CallBackData {
        
        private System.DateTime dataLeadCreationField;
        
        private string fileNameField;
        
        private string customerNameField;
        
        private string customerSurnameField;
        
        private string addressField;
        
        private string zipCodeField;
        
        private string cityField;
        
        private string provinceField;
        
        private string nationField;
        
        private string eMailField;
        
        private string phoneNumberField;
        
        private string mobilePhoneNumberField;
        
        private System.Nullable<bool> flagPrivacyField;
        
        private string brandField;
        
        private string stockSearchedModelField;
        
        private System.DateTime dueDateField;
        
        private string typeContactField;
        
        private string modelField;
        
        private string typeField;
        
        private string gVWField;
        
        private string wheelTypeField;
        
        private string fuelField;
        
        private System.Nullable<bool> flagPrivacyDueField;
        
        private string idCareField;
        
        private string initiativeSourceField;
        
        private string initiativeSourceReportField;
        
        private string initiativeSourceReportDetailField;
        
        private string companyNameField;
        
        private string powerField;
        
        private string cabTypeField;
        
        private string suspensionField;
        
        private string commentWebFormField;
        
        private string idLeadSiteField;
        
        private string titleField;
        
        private string languageField;
        
        private string codePromotionField;
        
        private string modelOfInterestField;
        
        private System.DateTime desideredDataField;
        
        private string canaleField;
        
        /// <remarks/>
        public System.DateTime DataLeadCreation {
            get {
                return this.dataLeadCreationField;
            }
            set {
                this.dataLeadCreationField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerSurname {
            get {
                return this.customerSurnameField;
            }
            set {
                this.customerSurnameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public string Nation {
            get {
                return this.nationField;
            }
            set {
                this.nationField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNumber {
            get {
                return this.mobilePhoneNumberField;
            }
            set {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> FlagPrivacy {
            get {
                return this.flagPrivacyField;
            }
            set {
                this.flagPrivacyField = value;
            }
        }
        
        /// <remarks/>
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        public string StockSearchedModel {
            get {
                return this.stockSearchedModelField;
            }
            set {
                this.stockSearchedModelField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        public string TypeContact {
            get {
                return this.typeContactField;
            }
            set {
                this.typeContactField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string GVW {
            get {
                return this.gVWField;
            }
            set {
                this.gVWField = value;
            }
        }
        
        /// <remarks/>
        public string WheelType {
            get {
                return this.wheelTypeField;
            }
            set {
                this.wheelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Fuel {
            get {
                return this.fuelField;
            }
            set {
                this.fuelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> FlagPrivacyDue {
            get {
                return this.flagPrivacyDueField;
            }
            set {
                this.flagPrivacyDueField = value;
            }
        }
        
        /// <remarks/>
        public string IdCare {
            get {
                return this.idCareField;
            }
            set {
                this.idCareField = value;
            }
        }
        
        /// <remarks/>
        public string InitiativeSource {
            get {
                return this.initiativeSourceField;
            }
            set {
                this.initiativeSourceField = value;
            }
        }
        
        /// <remarks/>
        public string InitiativeSourceReport {
            get {
                return this.initiativeSourceReportField;
            }
            set {
                this.initiativeSourceReportField = value;
            }
        }
        
        /// <remarks/>
        public string InitiativeSourceReportDetail {
            get {
                return this.initiativeSourceReportDetailField;
            }
            set {
                this.initiativeSourceReportDetailField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
            }
        }
        
        /// <remarks/>
        public string CabType {
            get {
                return this.cabTypeField;
            }
            set {
                this.cabTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Suspension {
            get {
                return this.suspensionField;
            }
            set {
                this.suspensionField = value;
            }
        }
        
        /// <remarks/>
        public string CommentWebForm {
            get {
                return this.commentWebFormField;
            }
            set {
                this.commentWebFormField = value;
            }
        }
        
        /// <remarks/>
        public string IdLeadSite {
            get {
                return this.idLeadSiteField;
            }
            set {
                this.idLeadSiteField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string CodePromotion {
            get {
                return this.codePromotionField;
            }
            set {
                this.codePromotionField = value;
            }
        }
        
        /// <remarks/>
        public string ModelOfInterest {
            get {
                return this.modelOfInterestField;
            }
            set {
                this.modelOfInterestField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DesideredData {
            get {
                return this.desideredDataField;
            }
            set {
                this.desideredDataField = value;
            }
        }
        
        /// <remarks/>
        public string Canale {
            get {
                return this.canaleField;
            }
            set {
                this.canaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SetAppointmentCompletedEventHandler(object sender, SetAppointmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAppointmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetAppointmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetAppointmentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetAppointmentResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetCalendarCompletedEventHandler(object sender, GetCalendarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCalendarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCalendarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetCalendarResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetCalendarResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SetDealerCompletedEventHandler(object sender, SetDealerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetDealerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDealerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetDealerResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetDealerResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetDealerCompletedEventHandler(object sender, GetDealerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDealerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDealerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDealerResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDealerResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591