//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4211
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reply.Iveco.LeadManagement.Web.UI.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:29540/services/LeadManagementServices.asmx")]
        public string Reply_Iveco_LeadManagement_Web_UI_Test_LeadManagementServiceBasic_LeadManagementServices {
            get {
                return ((string)(this["Reply_Iveco_LeadManagement_Web_UI_Test_LeadManagementServiceBasic_LeadManagementS" +
                    "ervices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.88.22/CustomLMCERT/Services/LeadManagementServices.asmx")]
        public string Reply_Iveco_LeadManagement_Web_UI_Test_LeadManagementServiceBase_LeadManagementServices {
            get {
                return ((string)(this["Reply_Iveco_LeadManagement_Web_UI_Test_LeadManagementServiceBase_LeadManagementSe" +
                    "rvices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:29540/services/CrmDealerServices.asmx")]
        public string Reply_Iveco_LeadManagement_Web_UI_Test_CrmDealerServices_CrmDealerServices {
            get {
                return ((string)(this["Reply_Iveco_LeadManagement_Web_UI_Test_CrmDealerServices_CrmDealerServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:29540/services/LeadManagementMobileService.asmx")]
        public string Reply_Iveco_LeadManagement_Web_UI_Test_CrmMobileService_LeadManagementMobileService {
            get {
                return ((string)(this["Reply_Iveco_LeadManagement_Web_UI_Test_CrmMobileService_LeadManagementMobileServi" +
                    "ce"]));
            }
        }
    }
}
