#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reply.Seat.InvioSmsCrm.DataAccess.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="MarketingSEAT_MSCRM")]
	public partial class MarketingSeatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MarketingSeatDataContext() : 
				base(global::Reply.Seat.InvioSmsCrm.DataAccess.Properties.Settings.Default.MarketingSEAT_MSCRMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingSeatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingSeatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingSeatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingSeatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<New_sms> New_sms
		{
			get
			{
				return this.GetTable<New_sms>();
			}
		}
	}
	
	[Table(Name="dbo.New_sms")]
	public partial class New_sms
	{
		
		private System.Nullable<int> _CreatedByDsc;
		
		private string _CreatedByName;
		
		private System.Nullable<int> _ModifiedByDsc;
		
		private string _ModifiedByName;
		
		private System.Nullable<int> _New_ChiamanteCampagnaIdDsc;
		
		private string _New_ChiamanteCampagnaIdName;
		
		private System.Nullable<System.Guid> _OwnerId;
		
		private string _OwnerIdName;
		
		private string _OwnerIdYomiName;
		
		private System.Nullable<int> _OwnerIdDsc;
		
		private System.Nullable<int> _OwnerIdType;
		
		private System.Guid _New_smsId;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<System.Guid> _CreatedBy;
		
		private System.Nullable<System.DateTime> _ModifiedOn;
		
		private System.Nullable<System.Guid> _ModifiedBy;
		
		private System.Nullable<System.Guid> _OwningUser;
		
		private System.Nullable<System.Guid> _OwningBusinessUnit;
		
		private int _statecode;
		
		private System.Nullable<int> _statuscode;
		
		private System.Nullable<int> _DeletionStateCode;
		
		private System.Data.Linq.Binary _VersionNumber;
		
		private System.Nullable<int> _ImportSequenceNumber;
		
		private System.Nullable<System.DateTime> _OverriddenCreatedOn;
		
		private System.Nullable<int> _TimeZoneRuleVersionNumber;
		
		private System.Nullable<int> _UTCConversionTimeZoneCode;
		
		private string _New_name;
		
		private System.Nullable<System.Guid> _New_ChiamanteCampagnaId;
		
		private string _New_TestoSMS;
		
		private string _New_NumeroDestinatario;
		
		private System.Nullable<System.DateTime> _New_DataInvio;
		
		private System.Nullable<int> _New_StatoInvio;
		
		private string _New_DescrizioneErrore;
		
		public New_sms()
		{
		}
		
		[Column(Storage="_CreatedByDsc", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CreatedByDsc
		{
			get
			{
				return this._CreatedByDsc;
			}
			set
			{
				if ((this._CreatedByDsc != value))
				{
					this._CreatedByDsc = value;
				}
			}
		}
		
		[Column(Storage="_CreatedByName", DbType="NVarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string CreatedByName
		{
			get
			{
				return this._CreatedByName;
			}
			set
			{
				if ((this._CreatedByName != value))
				{
					this._CreatedByName = value;
				}
			}
		}
		
		[Column(Storage="_ModifiedByDsc", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ModifiedByDsc
		{
			get
			{
				return this._ModifiedByDsc;
			}
			set
			{
				if ((this._ModifiedByDsc != value))
				{
					this._ModifiedByDsc = value;
				}
			}
		}
		
		[Column(Storage="_ModifiedByName", DbType="NVarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string ModifiedByName
		{
			get
			{
				return this._ModifiedByName;
			}
			set
			{
				if ((this._ModifiedByName != value))
				{
					this._ModifiedByName = value;
				}
			}
		}
		
		[Column(Storage="_New_ChiamanteCampagnaIdDsc", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> New_ChiamanteCampagnaIdDsc
		{
			get
			{
				return this._New_ChiamanteCampagnaIdDsc;
			}
			set
			{
				if ((this._New_ChiamanteCampagnaIdDsc != value))
				{
					this._New_ChiamanteCampagnaIdDsc = value;
				}
			}
		}
		
		[Column(Storage="_New_ChiamanteCampagnaIdName", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string New_ChiamanteCampagnaIdName
		{
			get
			{
				return this._New_ChiamanteCampagnaIdName;
			}
			set
			{
				if ((this._New_ChiamanteCampagnaIdName != value))
				{
					this._New_ChiamanteCampagnaIdName = value;
				}
			}
		}
		
		[Column(Storage="_OwnerId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> OwnerId
		{
			get
			{
				return this._OwnerId;
			}
			set
			{
				if ((this._OwnerId != value))
				{
					this._OwnerId = value;
				}
			}
		}
		
		[Column(Storage="_OwnerIdName", DbType="NVarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string OwnerIdName
		{
			get
			{
				return this._OwnerIdName;
			}
			set
			{
				if ((this._OwnerIdName != value))
				{
					this._OwnerIdName = value;
				}
			}
		}
		
		[Column(Storage="_OwnerIdYomiName", DbType="NVarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string OwnerIdYomiName
		{
			get
			{
				return this._OwnerIdYomiName;
			}
			set
			{
				if ((this._OwnerIdYomiName != value))
				{
					this._OwnerIdYomiName = value;
				}
			}
		}
		
		[Column(Storage="_OwnerIdDsc", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> OwnerIdDsc
		{
			get
			{
				return this._OwnerIdDsc;
			}
			set
			{
				if ((this._OwnerIdDsc != value))
				{
					this._OwnerIdDsc = value;
				}
			}
		}
		
		[Column(Storage="_OwnerIdType", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> OwnerIdType
		{
			get
			{
				return this._OwnerIdType;
			}
			set
			{
				if ((this._OwnerIdType != value))
				{
					this._OwnerIdType = value;
				}
			}
		}
		
		[Column(Storage="_New_smsId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid New_smsId
		{
			get
			{
				return this._New_smsId;
			}
			set
			{
				if ((this._New_smsId != value))
				{
					this._New_smsId = value;
				}
			}
		}
		
		[Column(Storage="_CreatedOn", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this._CreatedOn = value;
				}
			}
		}
		
		[Column(Storage="_CreatedBy", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[Column(Storage="_ModifiedOn", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this._ModifiedOn = value;
				}
			}
		}
		
		[Column(Storage="_ModifiedBy", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[Column(Storage="_OwningUser", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> OwningUser
		{
			get
			{
				return this._OwningUser;
			}
			set
			{
				if ((this._OwningUser != value))
				{
					this._OwningUser = value;
				}
			}
		}
		
		[Column(Storage="_OwningBusinessUnit", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> OwningBusinessUnit
		{
			get
			{
				return this._OwningBusinessUnit;
			}
			set
			{
				if ((this._OwningBusinessUnit != value))
				{
					this._OwningBusinessUnit = value;
				}
			}
		}
		
		[Column(Storage="_statecode", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int statecode
		{
			get
			{
				return this._statecode;
			}
			set
			{
				if ((this._statecode != value))
				{
					this._statecode = value;
				}
			}
		}
		
		[Column(Storage="_statuscode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> statuscode
		{
			get
			{
				return this._statuscode;
			}
			set
			{
				if ((this._statuscode != value))
				{
					this._statuscode = value;
				}
			}
		}
		
		[Column(Storage="_DeletionStateCode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DeletionStateCode
		{
			get
			{
				return this._DeletionStateCode;
			}
			set
			{
				if ((this._DeletionStateCode != value))
				{
					this._DeletionStateCode = value;
				}
			}
		}
		
		[Column(Storage="_VersionNumber", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this._VersionNumber = value;
				}
			}
		}
		
		[Column(Storage="_ImportSequenceNumber", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this._ImportSequenceNumber;
			}
			set
			{
				if ((this._ImportSequenceNumber != value))
				{
					this._ImportSequenceNumber = value;
				}
			}
		}
		
		[Column(Storage="_OverriddenCreatedOn", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this._OverriddenCreatedOn;
			}
			set
			{
				if ((this._OverriddenCreatedOn != value))
				{
					this._OverriddenCreatedOn = value;
				}
			}
		}
		
		[Column(Storage="_TimeZoneRuleVersionNumber", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this._TimeZoneRuleVersionNumber;
			}
			set
			{
				if ((this._TimeZoneRuleVersionNumber != value))
				{
					this._TimeZoneRuleVersionNumber = value;
				}
			}
		}
		
		[Column(Storage="_UTCConversionTimeZoneCode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this._UTCConversionTimeZoneCode;
			}
			set
			{
				if ((this._UTCConversionTimeZoneCode != value))
				{
					this._UTCConversionTimeZoneCode = value;
				}
			}
		}
		
		[Column(Storage="_New_name", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string New_name
		{
			get
			{
				return this._New_name;
			}
			set
			{
				if ((this._New_name != value))
				{
					this._New_name = value;
				}
			}
		}
		
		[Column(Storage="_New_ChiamanteCampagnaId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> New_ChiamanteCampagnaId
		{
			get
			{
				return this._New_ChiamanteCampagnaId;
			}
			set
			{
				if ((this._New_ChiamanteCampagnaId != value))
				{
					this._New_ChiamanteCampagnaId = value;
				}
			}
		}
		
		[Column(Storage="_New_TestoSMS", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string New_TestoSMS
		{
			get
			{
				return this._New_TestoSMS;
			}
			set
			{
				if ((this._New_TestoSMS != value))
				{
					this._New_TestoSMS = value;
				}
			}
		}
		
		[Column(Storage="_New_NumeroDestinatario", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string New_NumeroDestinatario
		{
			get
			{
				return this._New_NumeroDestinatario;
			}
			set
			{
				if ((this._New_NumeroDestinatario != value))
				{
					this._New_NumeroDestinatario = value;
				}
			}
		}
		
		[Column(Storage="_New_DataInvio", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> New_DataInvio
		{
			get
			{
				return this._New_DataInvio;
			}
			set
			{
				if ((this._New_DataInvio != value))
				{
					this._New_DataInvio = value;
				}
			}
		}
		
		[Column(Storage="_New_StatoInvio", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> New_StatoInvio
		{
			get
			{
				return this._New_StatoInvio;
			}
			set
			{
				if ((this._New_StatoInvio != value))
				{
					this._New_StatoInvio = value;
				}
			}
		}
		
		[Column(Storage="_New_DescrizioneErrore", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string New_DescrizioneErrore
		{
			get
			{
				return this._New_DescrizioneErrore;
			}
			set
			{
				if ((this._New_DescrizioneErrore != value))
				{
					this._New_DescrizioneErrore = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
