//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4206.
// 
#pragma warning disable 1591

namespace Reply.Iveco.LeadManagement.Web.UI.Test.MyLeadService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CrmDealerServicesSoap", Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class CrmDealerServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetLeadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CrmDealerServices() {
            this.Url = global::Reply.Iveco.LeadManagement.Web.UI.Test.Properties.Settings.Default.Reply_Iveco_LeadManagement_Web_UI_Test_MyLeadService_CrmDealerServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetLeadCompletedEventHandler SetLeadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("_http://schemas.microsoft.com/crm/2006/WebServices/SetLead", RequestNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", ResponseNamespace="_http://schemas.microsoft.com/crm/2006/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetLeadResult SetLead(ContactLead lead, string orgName) {
            object[] results = this.Invoke("SetLead", new object[] {
                        lead,
                        orgName});
            return ((SetLeadResult)(results[0]));
        }
        
        /// <remarks/>
        public void SetLeadAsync(ContactLead lead, string orgName) {
            this.SetLeadAsync(lead, orgName, null);
        }
        
        /// <remarks/>
        public void SetLeadAsync(ContactLead lead, string orgName, object userState) {
            if ((this.SetLeadOperationCompleted == null)) {
                this.SetLeadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLeadOperationCompleted);
            }
            this.InvokeAsync("SetLead", new object[] {
                        lead,
                        orgName}, this.SetLeadOperationCompleted, userState);
        }
        
        private void OnSetLeadOperationCompleted(object arg) {
            if ((this.SetLeadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLeadCompleted(this, new SetLeadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class ContactLead {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        private string iDLeadExternalField;
        
        private string iDLeadCRMLeadField;
        
        private string canaleField;
        
        private string campagnaField;
        
        private string customer_NameField;
        
        private string customer_SurnameField;
        
        private string company_NameField;
        
        private string businessTypeField;
        
        private string jobDescriptionField;
        
        private string addressField;
        
        private string cityField;
        
        private string zipCodeField;
        
        private string enderecoPostalField;
        
        private string hamletField;
        
        private string provinceField;
        
        private string customerCountryField;
        
        private string phoneNumberField;
        
        private string mobilePhoneNumberField;
        
        private string officeNumberField;
        
        private string faxField;
        
        private string emailField;
        
        private System.Nullable<System.DateTime> profilingDataHField;
        
        private System.Nullable<bool> criticalCustomerField;
        
        private string codicePromozioneField;
        
        private System.Nullable<bool> flagPrivacyField;
        
        private string motivazioneCriticalCustomerField;
        
        private string typeContactField;
        
        private string notaProdottoDiInteresseField;
        
        private string notaUsatoField;
        
        private string notaClienteField;
        
        private string vATCodeField;
        
        private string tAXCodeField;
        
        private string legalFormField;
        
        private string numberOfEmployeesField;
        
        private string annualRevenueField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IDLeadExternal {
            get {
                return this.iDLeadExternalField;
            }
            set {
                this.iDLeadExternalField = value;
            }
        }
        
        /// <remarks/>
        public string IDLeadCRMLead {
            get {
                return this.iDLeadCRMLeadField;
            }
            set {
                this.iDLeadCRMLeadField = value;
            }
        }
        
        /// <remarks/>
        public string Canale {
            get {
                return this.canaleField;
            }
            set {
                this.canaleField = value;
            }
        }
        
        /// <remarks/>
        public string Campagna {
            get {
                return this.campagnaField;
            }
            set {
                this.campagnaField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Name {
            get {
                return this.customer_NameField;
            }
            set {
                this.customer_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Surname {
            get {
                return this.customer_SurnameField;
            }
            set {
                this.customer_SurnameField = value;
            }
        }
        
        /// <remarks/>
        public string Company_Name {
            get {
                return this.company_NameField;
            }
            set {
                this.company_NameField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
            }
        }
        
        /// <remarks/>
        public string JobDescription {
            get {
                return this.jobDescriptionField;
            }
            set {
                this.jobDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EnderecoPostal {
            get {
                return this.enderecoPostalField;
            }
            set {
                this.enderecoPostalField = value;
            }
        }
        
        /// <remarks/>
        public string Hamlet {
            get {
                return this.hamletField;
            }
            set {
                this.hamletField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCountry {
            get {
                return this.customerCountryField;
            }
            set {
                this.customerCountryField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNumber {
            get {
                return this.mobilePhoneNumberField;
            }
            set {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeNumber {
            get {
                return this.officeNumberField;
            }
            set {
                this.officeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ProfilingDataH {
            get {
                return this.profilingDataHField;
            }
            set {
                this.profilingDataHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CriticalCustomer {
            get {
                return this.criticalCustomerField;
            }
            set {
                this.criticalCustomerField = value;
            }
        }
        
        /// <remarks/>
        public string CodicePromozione {
            get {
                return this.codicePromozioneField;
            }
            set {
                this.codicePromozioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> FlagPrivacy {
            get {
                return this.flagPrivacyField;
            }
            set {
                this.flagPrivacyField = value;
            }
        }
        
        /// <remarks/>
        public string MotivazioneCriticalCustomer {
            get {
                return this.motivazioneCriticalCustomerField;
            }
            set {
                this.motivazioneCriticalCustomerField = value;
            }
        }
        
        /// <remarks/>
        public string TypeContact {
            get {
                return this.typeContactField;
            }
            set {
                this.typeContactField = value;
            }
        }
        
        /// <remarks/>
        public string NotaProdottoDiInteresse {
            get {
                return this.notaProdottoDiInteresseField;
            }
            set {
                this.notaProdottoDiInteresseField = value;
            }
        }
        
        /// <remarks/>
        public string NotaUsato {
            get {
                return this.notaUsatoField;
            }
            set {
                this.notaUsatoField = value;
            }
        }
        
        /// <remarks/>
        public string NotaCliente {
            get {
                return this.notaClienteField;
            }
            set {
                this.notaClienteField = value;
            }
        }
        
        /// <remarks/>
        public string VATCode {
            get {
                return this.vATCodeField;
            }
            set {
                this.vATCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TAXCode {
            get {
                return this.tAXCodeField;
            }
            set {
                this.tAXCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LegalForm {
            get {
                return this.legalFormField;
            }
            set {
                this.legalFormField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfEmployees {
            get {
                return this.numberOfEmployeesField;
            }
            set {
                this.numberOfEmployeesField = value;
            }
        }
        
        /// <remarks/>
        public string AnnualRevenue {
            get {
                return this.annualRevenueField;
            }
            set {
                this.annualRevenueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="_http://schemas.microsoft.com/crm/2006/WebServices")]
    public partial class SetLeadResult {
        
        private bool isSuccessfulField;
        
        private string errorDescriptionField;
        
        private string errorCodeField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void SetLeadCompletedEventHandler(object sender, SetLeadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetLeadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetLeadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetLeadResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetLeadResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591