<?xml version="1.0" encoding="utf-8"?><Database Name="MarketingSEAT_MSCRM" Class="MarketingSeatDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=174.129.188.203;Initial Catalog=MarketingSEAT_MSCRM;Persist Security Info=True;User ID=d.trotta" SettingsObjectName="Reply.Seat.DinamichePromozionali.DataAccess.Properties.Settings" SettingsPropertyName="MarketingSEAT_MSCRMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Campaign" Member="Campaigns">
    <Type Name="Campaign">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="PriceListDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceListName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProposedEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BudgetedCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PromotionCodeName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PriceListId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsTemplate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CampaignId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ActualStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TotalActualCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExpectedRevenue" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="CodeName" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="ProposedStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Objective" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActualEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OtherCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalCampaignActivityActualCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpectedResponse" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalCampaignActivityActualCost_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="BudgetedCost_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ExpectedRevenue_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OtherCost_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TotalActualCost_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="New_TipoRedenption" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ValoreRedenption" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_TipoTarget" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_CodiceCampagna" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="New_Comunicazione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_NumeroChiamateSoglia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_DataInizioSoglia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_DataFineSoglia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_FasciaOraria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Lunedi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Martedi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Mercoledi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Giovedi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Venerdi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Sabato" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Domenica" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_MessaggioRichiestaPrivacy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_MessaggioPushAPStatusconPrivacy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_MessaggioVincitaAP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_MessaggioVincitaClienteSMS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_MessaggioVincitaClienteEmail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_PeriodoSoglia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Canale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_VincitaAPFisso" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_VincitaAPMobile" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_DataIniziofascia1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_DataFinefascia1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_DataIniziofascia2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_DataFinefascia2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_DataIniziofascia3" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_DataFinefascia3" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_Fascia1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Fascia2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Fascia3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_LogoBanner" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_LogoPrivacy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_LogoCampagnaPush" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_LogoCampagnaVincita" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_DecrementaTrasferimento" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Servizio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Classe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ClusterCRM" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.new_campaign_new_calltype" Member="new_campaign_new_calltypes">
    <Type Name="new_campaign_new_calltype">
      <Column Name="new_campaign_new_calltypeId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="campaignid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="new_calltypeid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.New_numeratore" Member="New_numeratores">
    <Type Name="New_numeratore">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_numeratoreId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_Anno" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="New_Contatore" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.new_campaign_new_premio" Member="new_campaign_new_premios">
    <Type Name="new_campaign_new_premio">
      <Column Name="new_campaign_new_premioId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="campaignid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="new_premioid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.New_codicepromozionale" Member="New_codicepromozionales">
    <Type Name="New_codicepromozionale">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_TemplatePremioIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_TemplatePremioIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_codicepromozionaleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_codice" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_TemplatePremioId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_Partner" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_Usato" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_oggetto" Member="New_oggettos">
    <Type Name="New_oggetto">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_TemplatePremioIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_TemplatePremioIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_oggettoId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_codice" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_TemplatePremioId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_Usato" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_premio" Member="New_premios">
    <Type Name="New_premio">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_premioId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_TipologiaPremio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Descrizione" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_mcv_sms" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_mcv_email" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_mcv_domicilio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_datascadenza" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_GiorniValidita" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_quantita" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Dataattivazionepremio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Dataattivazione" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_FiltroDataAttivazione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_PremioRicorrente" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="New_TipoNumeriche" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ModalitaComPremio" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_calltype" Member="New_calltypes">
    <Type Name="New_calltype">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_calltypeId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_nomecalltype" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="New_Servizio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Descrizione" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_Cifratura" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Descrizioneestesa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="New_Classe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ClusterCRM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_CallTypeTrasferito" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_Privacy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_call" Member="New_calls">
    <Type Name="New_call">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_callId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.List" Member="Lists">
    <Type Name="List">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MemberCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="LastUsedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ListId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DoNotSendOnOptOut" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IgnoreInactiveListMembers" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MemberType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CreatedFromCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="LockStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cost_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_chiamantecampagna" Member="New_chiamantecampagnas">
    <Type Name="New_chiamantecampagna">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="New_CampagnaIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_CampagnaIdName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="New_PartecipanteIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_PartecipanteIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="New_PartecipanteIdYomiName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_chiamantecampagnaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_CampagnaId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_StatoPartecipante" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_VinciteRimanenti" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_PartecipanteId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_Privacy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ChiamateEffettuate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ChiamateResidue" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_callgratuita" Member="New_callgratuitas">
    <Type Name="New_callgratuita">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_TemplatePremioIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_TemplatePremioIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_callgratuitaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_codice" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_TemplatePremioId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_NumeroCalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_Usato" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_Cluster800" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_DataInizioPromozione" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_DataFinePromozione" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lead" Member="Leads">
    <Type Name="Lead">
      <Column Name="AccountIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="AccountIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="CampaignIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CampaignIdName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ContactIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ContactIdYomiName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="MasterLeadIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MasterLeadIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="MasterLeadIdYomiName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="new_calltypeidDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="new_calltypeidName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address1_AddressId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Address1_AddressTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address1_Line1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address1_Line2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address1_Line3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address1_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_StateOrProvince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_PostOfficeBox" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address1_PostalCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address1_UTCOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1_UPSZone" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Address1_Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address1_Telephone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address1_ShippingMethodCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1_Telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_Telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_AddressId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Address2_AddressTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address2_Line1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address2_Line2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address2_Line3" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address2_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_StateOrProvince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_PostOfficeBox" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address2_PostalCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address2_UTCOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2_UPSZone" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Address2_Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address2_Telephone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address2_ShippingMethodCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2_Telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_Telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CustomerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="CustomerIdYomiName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="CustomerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeadId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LeadSourceCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeadQualityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriorityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IndustryCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreferredContactMethodCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalesStageCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningTeam" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ParticipatesInWorkflow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EstimatedValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EstimatedCloseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Revenue" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NumberOfEmployees" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoNotPhone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SIC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DoNotFax" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EMailAddress1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Salutation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DoNotEMail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EMailAddress2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DoNotPostalMail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EMailAddress3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="YomiFirstName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="WebSiteUrl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Telephone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsPrivate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YomiMiddleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="YomiLastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="YomiFullName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pager" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="MasterId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CampaignId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DoNotSendMM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Merged" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DoNotBulkEMail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUsedInCampaign" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="EstimatedAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="EstimatedAmount_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Revenue_Base" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="YomiCompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_CodiceCifratoPartecipante" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_Privacy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="new_calltypeid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_Privacy12" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_sms" Member="New_sms">
    <Type Name="New_sm">
      <Column Name="CreatedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_smsId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletionStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="New_ChiamanteCampagnaId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="New_TestoSMS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_NumeroDestinatario" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="New_DataInvio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="New_StatoInvio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="New_DescrizioneErrore" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>